#!/bin/bash

# default duration of 4 hours
if [ $# == 1 ]; then
  hours=$1
else
  hours=4
fi

duration=$(expr "$hours" '*' "60")

# set bitwarden session
session="$(bw unlock --raw)"

# annoyingly enough, bw unlock will print either the session key or "Invalid Master Password" to stdout
# the only way to tell which one it did is to use the exit code
if [ $? != 0 ]; then
  echo "$session"
  exit 1
fi

set -euo pipefail

# grab private key from secret
ssh-add -t $duration <(BW_SESSION=$session bw get item github.com | jq .notes -r)
